version: '3.8'

services:
  app:
    container_name: dhafer-backoffice
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    network_mode: "host"
    env_file:
      - .env
    volumes:
      - /var/www/images:/var/www/images