version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3001:3001"
    env_file:
      - .env
    networks:
      - app-network

networks:
  app-network:
    driver: bridge